name: Deploy

on:
  push:
    branches: [ docker_CD ]
  pull_request:
    branches: [ docker_CD ]
 
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAUTE5BGDUMOP3UM7K
        aws-secret-access-key: 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
        aws-region: us-east-1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: deploy to cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBECONFIG: ./KUBECONFIG
        DOCKER_REGISTRY: hub.docker.com
        DOCKERHUB_REPOSITORY: wwa-app
        IMAGE_TAG: v1
      with:
        args: set image deployment/$DOCKERHUB_REPOSITORY $DOCKERHUB_REPOSITORY=$DOCKER_REGISTRY/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
        
    - name: verify deployment
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBECONFIG: ./KUBECONFIG
      with:
        args: rollout status deployment/wwa-app
