name: Deploy

on:
  push:
    branches: [ docker_CD ]
  pull_request:
    branches: [ docker_CD ]
 
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAUTE5BGDUMOP3UM7K
        aws-secret-access-key: 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
        aws-region: us-east-1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Install and configure kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: deploy to cluster
      env:
        DOCKER_REGISTRY: hub.docker.com
        DOCKER_REPOSITORY: wwa-app
        IMAGE_TAG: v1
      run: |
        export DOCKER_REPOSITORY=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}
        export IMAGE_TAG=${{ env.IMAGE_TAG }}
        export KUBECONFIG=${{secrets.KUBECONFIG}}
        envsubst < k8s/kustomization.tmpl.yaml > k8s/kustomization.yaml
        kubectl kustomize k8s | kubectl apply -f -
          
    - name: verify deployment
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: rollout status deployment/wwa-app
