name: Deploy

on:
  push:
    branches: [ docker_CD ]
  pull_request:
    branches: [ docker_CD ]

jobs:

  job:
    name: run multiple jobs
    runs-on: ubuntu-latest
    steps:
      - name: docker CI
        uses: ./.github/workflows/docker-image-build-push.yaml
      
      - name: AWS deploy
        uses: ./.github/workflows/aws.yaml
 
