name: Deploy

on:
  push:
    branches: [ docker_CD ]
  pull_request:
    branches: [ docker_CD ]




jobs:
  sonar_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Config for SaaST
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          config_files: ./devopslecturer/awmsc2022/.github/workflows/SonarQube.yml # default is .github/your.yml
  
  pytest:
    runs-on: ubuntu-latest
    needs: sonar_testing
    steps:
      - name: unit testing
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          config_files: ./devopslecturer/awmsc2022/.github/workflows/pytest.yml
          
  Jmeter-testing:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Jemeter testing
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          config_files: ./devopslecturer/awmsc2022/.github/workflows/Jmeter.yml 
          
  snyk-testing:
    runs-on: ubuntu-latest
    needs: Jmeter-testing
    steps:
      - name: snyk security testing
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          config_files: ./devopslecturer/awmsc2022/.github/workflows/snyk.yml 
  
  docker-CI:
    runs-on: ubuntu-latest
    needs: snyk-testing
    steps:
      - name: Config for docker CI
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          config_files: .github/workflows/docker-image-build-push.yml 
          
  deploy:
    runs-on: ubuntu-latest
    needs: docker-CI
    steps:
      - name: Config for deploy
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          config_files: ./devopslecturer/awmsc2022/.github/workflows/aws.yml 
  
  documentation:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Config for deploy
        uses: Monorepo-Actions/config-for-actions@v1.0.0
        with:
          config_files: ./devopslecturer/awmsc2022/.github/workflows/Sphinx.yml 
 
