name: Deploy

on:
  push:
    branches: [ docker_CD ]
  pull_request:
    branches: [ docker_CD ]




jobs:
  docker-CI:
    uses: devopslecturer/awmsc2022/.github/workflows/docker-image-build-push.yml@docker_CD
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
          
  deploy:
    needs: docker-CI
    uses: devopslecturer/awmsc2022/.github/workflows/aws.yml@docker_CD
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_USERNAME }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
