name: Deploy

on:
  push:
    branches: [ docker_CD ]
  pull_request:
    branches: [ docker_CD ]

jobs:
  job1:
    uses: ./.github/workflows/docker-image-build-push.yaml

  job2:
    needs: job1
    uses: ./.github/workflows/aws.yml
 
